name: Email Step Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 22f3003000@ds.study.iitm.ac.in
        run: |
          echo "Hello, world!"
          echo "Workflow executed successfully!"
